# Generated by Django 5.2.8 on 2025-11-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=50)),
                ('color_vehiculo', models.CharField(choices=[('1', 'ROJO'), ('2', 'AZUL'), ('3', 'VERDE')], max_length=1)),
                ('modelo', models.IntegerField()),
            ],
        ),
    ]
